name: Auto Deploy Lab1

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Running Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Compile code
        run: ./gradlew build

  deploy:
    runs-on: ubuntu-latest
    name: Deploy the JAR file to server
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build Application
        run: ./gradlew build
      - name: Deploy package to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "build/libs/webapilab1-0.0.1-SNAPSHOT.jar"
          target: "INT493lab1"
      - name: Strat Application
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            # move to directory that collect the application file
            cd /home/azureuser/INT493lab1/build/libs
            # kill old task background
            kill $(pidof java)
            # run application on background
            java -jar webapilab1-0.0.1-SNAPSHOT.jar > app.log 2>&1 </dev/null &
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
