name: Auto Deploy Lab1

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Running Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Compile code
        run: ./gradlew build

  deploy:
    runs-on: ubuntu-latest
    name: Deploy the JAR file to the remote server
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Generate the package
        run: ./gradlew build
      - name: Deploy the package to the remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "build/libs/webapilab1-0.0.1-SNAPSHOT.jar"
          target: "INT493lab1"
      - name: Run a script on remote server (start the application)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
          command_timeout: 1m
          script: |
            # Rename
            cd /INT493lab1/build/libs
            # Kill old process
            kill $(pidof java)
            # Start application on background process
            java -jar webapilab1-0.0.1-SNAPSHOT.jar > app.log 2>&1 </dev/null &
